name: "combine-prs"
description: "Combine multiple PRs into a single PR"
author: "Grant Birkinbine"
branding:
  icon: 'git-branch'
  color: 'gray-dark'
inputs:
  github_token:
    description: The GitHub token used to create an authenticated client - Provided for you by default!
    default: ${{ github.token }}
    required: true
  branch_prefix:
    description: The prefix of the branches to combine
    required: true
    default: dependabot
  pr_title:
    description: The title of the pull request to create
    required: true
    default: "Combined PRs"
  pr_body_header:
    description: The header of the pull request body
    required: true
    default: "# Combined PRs ➡️📦⬅️"
  min_combine_number:
    description: The minimum number of PRs that have to match criteria in order to create a combined PR
    required: true
    default: "2"
  branch_regex:
    description: The regex to match the branches to combine - more control than branch_prefix
    required: false
    default: ""
  ci_required:
    description: Whether or not CI should be passing to combine the PR
    required: true
    default: "true"
  review_required:
    description: Whether or not a review should be required to combine the PR
    required: false
    default: "false"
  combine_branch_name:
    description: The name of the branch to combine the PRs into
    required: true
    default: "combined-prs-branch"
  ignore_label:
    description: The label to ignore when combining PRs
    required: true
    default: "nocombine"
  select_label:
    description: The label marking PRs that should be combined
    required: false
    default: ""
  labels:
    description: A comma seperated list of labels to add to the combined PR
    required: false
    default: ""
  autoclose:
    description: Whether or not to close combined PRs if the combined PR is merged
    required: false
    default: "true"
  update_branch:
    description: Whether or not to update the combined branch with the latest changes from the base branch after creating the combined pull request
    default: "true"
    required: false
  create_from_scratch:
    description: Whether or not to start from a clean base branch when (re)creating the combined PR
    default: "false"
    required: false
outputs:
  pr_url:
    description: The pull request URL if a PR was created
  pr_number:
    description: The pull request number if a PR was created
runs:
  using: "node20"
  main: "dist/index.js"
